{
        materials:[
        {
        name:'plants_model:Plane043SG.009',
        parameters:[
        {
        baseColor:'plants_tex',
        },
        {
        baseColorTint:[
        1,
        1,
        1,
        1,
        ],
        },
        {
        metallic:0,
        },
        {
        roughness:1,
        },
        {
        opacity:null,
        },
        ],
        source:'build/sceneform_sdk/default_materials/obj_material.sfm',
        },
        ],
        model:{
        attributes:[
        'Position',
        'TexCoord',
        'Orientation',
        ],
        collision:{},
        file:'sampledata/girasol0001.obj',
        name:'girasol0001',
        recenter:'root',
        scale:0.035681999999999998,
        },
